-- servicios: 1 por área con datos realistas
insert into public.servicios (area, label, categoria, descripcion, tags, precio_min, precio_max, tiempo_min, tiempo_max, complejidad, details_type, orden, activo) values
  ('derecho', 'Usucapión y Regularización de Derecho Propietario', 'Derecho Civil', 'Asesoría y patrocinio en procesos de usucapión (prescripción adquisitiva) y regularización del derecho propietario ante autoridades jurisdiccionales.', array['usucapión','prescripción adquisitiva','derecho propietario','regularización'], 3500, 12000, '6 meses', '18 meses', 'Alta', 'general', 1, true),
  ('derecho', 'Sucesiones y Derecho Hereditario', 'Derecho Civil', 'Trámites sucesorios: declaratoria de herederos, partición de bienes, testamentos y aceptación de herencia.', array['sucesiones','herencia','testamento','partición'], 2000, 8000, '3 meses', '12 meses', 'Media', 'general', 2, true),
  ('derecho', 'Derecho Registral y Notarial', 'Derecho Registral', 'Rectificación de registros, folios reales, minutas, escrituras públicas y trámites ante Derechos Reales.', array['derechos reales','registro','folio real','minuta','escritura'], 800, 5000, '1 mes', '6 meses', 'Baja', 'general', 3, true),
  ('catastro', 'Elaboración de Fichas Catastrales', 'Catastro', 'Levantamiento y llenado de fichas catastrales para predios urbanos y rurales, conforme a normativa municipal vigente.', array['ficha catastral','predio urbano','predio rural','levantamiento'], 1500, 6000, '1 semana', '1 mes', 'Media', 'general', 1, true),
  ('catastro', 'Valuación Catastral', 'Catastro', 'Avalúos técnicos: valor comercial, valor catastral y dictámenes periciales para fines impositivos, compra-venta o herencias.', array['avalúo','valor catastral','valor comercial','pericial'], 2000, 10000, '1 semana', '2 semanas', 'Media', 'general', 2, true),
  ('ordenamiento', 'Planes de Ordenamiento Territorial', 'Ordenamiento Territorial', 'Elaboración de planes municipales de ordenamiento territorial (PMOT), planes de uso de suelo y zonificación.', array['PMOT','ordenamiento territorial','uso de suelo','zonificación'], 15000, 60000, '6 meses', '24 meses', 'Alta', 'general', 1, true),
  ('ordenamiento', 'Estudios de Impacto Territorial', 'Ordenamiento Territorial', 'Evaluación de impacto territorial y ambiental para proyectos urbanos, industriales y de infraestructura.', array['impacto territorial','evaluación','proyecto urbano','infraestructura'], 5000, 25000, '2 meses', '6 meses', 'Alta', 'general', 2, true),
  ('geografia', 'Análisis Geoespacial y SIG', 'Geografía', 'Procesamiento, análisis y visualización de datos geoespaciales con herramientas SIG (QGIS, ArcGIS, PostGIS).', array['SIG','QGIS','PostGIS','análisis espacial','geoespacial'], 2000, 15000, '1 semana', '3 meses', 'Media', 'general', 1, true),
  ('topografia', 'Levantamiento Topográfico', 'Topografía', 'Levantamiento planimétrico y altimétrico con estación total, GNSS y drone para predios, vías y proyectos.', array['levantamiento','topografía','estación total','GNSS','drone'], 3000, 20000, '3 días', '2 semanas', 'Media', 'general', 1, true),
  ('topografia', 'Georreferenciación de Predios', 'Topografía', 'Georreferenciación de predios con GPS diferencial y equipos GNSS RTK para registros catastrales.', array['georreferenciación','GNSS RTK','predio','catastro'], 1500, 8000, '1 día', '1 semana', 'Baja', 'general', 2, true),
  ('geomatica', 'Desarrollo de Aplicaciones Web GIS', 'Geomática', 'Desarrollo de aplicaciones web geográficas con MapLibre, Leaflet, OpenLayers y frameworks modernos.', array['web gis','MapLibre','Leaflet','OpenLayers','mapa interactivo'], 8000, 40000, '1 mes', '6 meses', 'Alta', 'general', 1, true),
  ('software', 'Desarrollo de Software a Medida', 'Software', 'Aplicaciones web, APIs REST, sistemas de gestión territorial, dashboards y automatización de procesos.', array['desarrollo','software','web','API','dashboard'], 10000, 50000, '1 mes', '12 meses', 'Alta', 'general', 1, true),
  ('software', 'Consultoría Técnica en TI', 'Software', 'Asesoría en arquitectura de software, DevOps, migraciones cloud, seguridad informática y mejores prácticas.', array['consultoría','arquitectura','DevOps','cloud','seguridad'], 3000, 15000, '1 semana', '3 meses', 'Media', 'general', 2, true);

-- factores_precio: parámetros dinámicos para cotizador
insert into public.factores_precio (etiqueta, descripcion, parametros, activo) values
  ('Complejidad del proyecto', 'Ajusta el precio base según la complejidad técnica del servicio.', '[{"key":"complejidad","label":"Complejidad","tipo":"chips","requerido":true,"opciones":[{"label":"Baja","multiplicador":0.8,"ayuda":"Trabajo estándar, sin contratiempos"},{"label":"Media","multiplicador":1.0,"ayuda":"Dificultad moderada"},{"label":"Alta","multiplicador":1.5,"ayuda":"Alta complejidad técnica o jurídica"}]}]', true),
  ('Urgencia', 'Ajusta el precio según el plazo de entrega requerido.', '[{"key":"urgencia","label":"Urgencia","tipo":"chips","requerido":false,"opciones":[{"label":"Normal","multiplicador":1.0,"ayuda":"Plazo estándar"},{"label":"Urgente","multiplicador":1.3,"ayuda":"Reducción de hasta 50% del plazo"},{"label":"Inmediato","multiplicador":1.6,"ayuda":"Dedicación exclusiva, entrega récord"}]}]', true),
  ('Cobertura geográfica', 'Aplica cuando el trabajo requiere desplazamiento fuera del área metropolitana.', '[{"key":"ubicacion","label":"Ubicación","tipo":"chips","requerido":false,"opciones":[{"label":"Local","multiplicador":1.0,"ayuda":"Área metropolitana"},{"label":"Provincial","multiplicador":1.2,"ayuda":"Desplazamiento a provincia"},{"label":"Nacional","multiplicador":1.5,"ayuda":"Cobertura nacional o múltiples regiones"}]}]', true);

-- normativa: muestra representativa
insert into public.normativa (titulo, categoria, numero_norma, fecha_promulgacion, fecha_publicacion, estado, resumen, palabras_clave, activo) values
  ('Constitución Política del Estado', 'leyes', 'CPE', '2009-02-07', '2009-02-09', 'vigente', 'Constitución vigente de Bolivia, aprobada mediante referendo constitucional. Establece el Estado Plurinacional y reconoce los derechos territoriales de las naciones indígena originaria campesinas.', array['constitución','estado plurinacional','derechos territoriales','autonomías'], true),
  ('Código Civil Boliviano', 'codigos', 'Decreto Ley 12760', '1975-08-06', '1975-11-15', 'modificada', 'Código Civil vigente con modificaciones. Regula las relaciones jurídicas privadas, incluyendo derechos reales, obligaciones, contratos y sucesiones.', array['código civil','derechos reales','obligaciones','contratos','sucesiones'], true),
  ('Ley de Catastro Municipal', 'leyes', 'Ley 482', '2014-01-09', '2014-02-08', 'vigente', 'Regula el catastro multifinalitario en Bolivia, estableciendo los lineamientos técnicos y administrativos para el registro y actualización de la información catastral.', array['catastro','municipal','multifinalitario','registro predial'], true),
  ('Decreto Reglamentario Ley 482', 'decretos_reglamentarios', 'DS 2788', '2016-07-06', '2016-07-07', 'vigente', 'Reglamenta la Ley de Catastro Municipal, definiendo procedimientos técnicos para el levantamiento, actualización y administración catastral.', array['reglamento','catastro','DS 2788','procedimientos'], true),
  ('Ley de Ordenamiento Territorial', 'leyes', 'Ley 777', '2016-01-21', '2016-02-11', 'vigente', 'Establece el marco normativo para el ordenamiento territorial integral en Bolivia, abarcando la planificación territorial, urbana y el uso de suelo.', array['ordenamiento territorial','planificación','uso de suelo','Ley 777'], true);
